### ISSUE TITLE
HMAC mistmatch on file download

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#61]
see here https://socialbusinessworld.org/serve-file/e1479156942/l1479120183/da/c1/BAy1vrXQbBhQ4xbD7jaX_cwKFsH2kosoe4-G4XLg0Wg/5000/8992/file/1479120183offerte%20d'aiuto%20rete%20ecosol%20italiana.pdf

**Comment by michelesbw** [comment]
Link to entity https://socialbusinessworld.org/file/view/742905/questionario-offerte-di-aiuto-formato-pdf-per-consultazione-offline-e-successiva-compilazione-online

**Comment by michelesbw** [comment]
[OFFERTE D'AIUTO RETE ECOSOL ITALIANA.pdf](https://github.com/sbwtech/sbw/files/590384/OFFERTE.D.AIUTO.RETE.ECOSOL.ITALIANA.pdf)

**Comment by feroda** [comment]
is this fixed?
Or the file "OFFERTE D'AIUTO RETE ECOSOL ITALIANA.pdf" generates the bug, whereas the document online is fixed?

**Comment by michelesbw** [comment]
Not fixed yet (you can try uploading a file setting access level to Private)

**Comment by feroda** [comment]
I cannot reproduce the bug in beta

https://beta.socialbusinessworld.org/file/view/713846/offerte-daiuto-ai-terremotati uploaded as private files.

neither in production

https://socialbusinessworld.org/file/view/745460/offerte-daiuto-rete-ecosol-italiana-caricato-privato

unfortunately I cannot reproduce and I cannot spend more time on this bug :(

**Comment by feroda** [comment]
ok reproduced the bug at the urls above: changed the file name including the ' symbol

**Comment by feroda** [comment]
I am bit sure that I have spotted the issue! I believe that Elgg must really care of url encoding/decoding. I think that `elgg_normalize_urls` should quote every url. And there must be a corresponding decoding function at url routing level.

Going to demonstrate the problem for a file called `offerte d'aiuto.pdf` and published with ACL Private:

For the download url:
https://beta.socialbusinessworld.org/serve-file/e1479610952/l1479594248/da/c1/gArXx4yi8lW6sQI8vnxZqup6z5gpP-pvtflntA1pvZ0/140000/140635/file/1479594249offerte%20d'aiuto.pdf

I have printed the following debug info:
```
The problem is in the path length.
For the path: 140000/140635/file/1479594249offerte d'aiuto.pdf
Length: 53
If you count them they do not match! Probably the ' is encoded in some way
Bin2Hex is: 3134303030302f3134303633352f66696c652f313437393539343234396f666665727465206426233033393b616975746f2e706466

Data for hmac: a:6:{s:6:"cookie";s:26:"md3e9hlc961j1jpuivsqsfs0v2";s:11:"disposition";s:1:"a";s:7:"expires";i:1479610952;s:12:"last_updated";i:1479594248;s:4:"path";s:53:"140000/140635/file/1479594249offerte d'aiuto.pdf";s:10:"use_cookie";i:1;}
HMAC for data: 3aP78IPh_yCguHE0W645VVZgla7nAvRom0vS6Ky8HKM
HMAC mismatch
```

So, please note the "s:53" for the serialized value "140000/140635/file/1479594249offerte d'aiuto.pdf"
**IT SHOULD BE 48**.

If I compute it in the detail view of the file in fact it is 48:
https://beta.socialbusinessworld.org/file/view/713846/offerte-daiuto-ai-terremotati

```
Data for hmac: a:6:{s:6:"cookie";s:26:"md3e9hlc961j1jpuivsqsfs0v2";s:11:"disposition";s:1:"a";s:7:"expires";i:1479610952;s:12:"last_updated";i:1479594248;s:4:"path";s:48:"140000/140635/file/1479594249offerte d'aiuto.pdf";s:10:"use_cookie";i:1;}
HMAC for data:
gArXx4yi8lW6sQI8vnxZqup6z5gpP-pvtflntA1pvZ0
3134303030302f3134303633352f66696c652f313437393539343234396f666665727465206427616975746f2e706466
```

You can see also the hex representation of the string that is different (after many characters).

The root problem is the urlencoding IMVVVVVHO. Even to find a temporary workaround for me is difficult in this situation.

You can enable the debug info I have written above by doing a checkout of the branch issue-61 in the beta version of SBW in the `vendor/elgg/elgg` 

To be sent to the Elgg core team if confirmed.

**Comment by michelesbw** [comment]
I tried disabling all unbundled plugins in beta and this issue remains, it should be a core one. I'm gonna report this to core team.
Cheers

**Comment by feroda** [comment]
Yes pretty sure core bug. fixed sanitization is a must-have...

Pls post here the link to the issue you will create, so we can keep track and .... I can reply ;)

**Comment by michelesbw** [comment]
The link is above, @hypeJunction noticed it, thank you :)

**Comment by michelesbw** [comment]
Closing this, Has been reported to core who "mitigated" the issue in Elgg 2.3
